# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f29297fa441b79a4ee11ae78c7667c0921d37a0939d7458682e2a7afc2278205b13fb42a385fb5a0606ab1224bb8bf565d0556b5db26f1dd54d8384f81b235b

test:
  secret_key_base: 72a85eed927fc04b747adfa282ba089a610f40a650d9eeeb64679be7c64886967e0c9ffc206cfd3e659b06679cdce878144712422bdbfc958ddb30816b58df14

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
